### ISSUE TITLE
Skin resets to default after closing plugin

### ISSUE THREAD

**Issue by takeoffmymonkey** [dozius/triple-cheese-themes#2]
I did everything as described and com.u-he.TripleCheese.Preferences.txt file shows correctly both new default scheme and proper size properties, but after I close plugin and reopen it, it defaults to original orange skin though with new size (that I've set)

**Comment by dozius** [comment]
Seems to work fine here. Are you clicking "make default" in the context menu? Maybe ask for help at the [U-He forum](https://www.kvraudio.com/forum/viewforum.php?f=31). Someone might have already run into your problem before.

**Comment by takeoffmymonkey** [comment]
Thanks, I've found the problem. I mixed up naming of original .txt file with the new one.
Great skins!

**Comment by dozius** [comment]
Thanks! Glad you got it working.
